# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - main
  paths:
    include:
      - petstore/petstorepetservice/*
 

resources:
- repo: self

variables:
  imageRepository: 'petstorepetservice'
  containerRegistry: 'mypetstoreecr.azurecr.io'
  dockerfilePath: 'petstore/petstorepetservice/Dockerfile'
  tag: '$(Build.BuildId)'
  

stages:
- stage: Build
  displayName: Build 
  
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'MyAgentPool'
      demands:
        - agent.name -equals MyAgent 
    steps:

    - script: echo -n -e "{\"version\":\"$(Build.BuildNumber) - $(tag)\"}" > petstore/petstorepetservice/src/main/resources/version.json 
    
    - task: Maven@4
      continueOnError: true
      displayName: Build Spring Boot Jar
      inputs:
        mavenPomFile: 'petstore/petstorepetservice/pom.xml'
        publishJUnitResults: true
        testResultsFiles: 'petstore/petstorepetservice/target/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        javaHomeOption: 'JDKVersion'
        jdkDirectory: '8'
        jdkArchitectureOption: 'x64'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build an image and Push to ACR 
      inputs:
        containerRegistry: 'acr-azure-devops-connection'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
          latest
