apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-petstoreserviceproduct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-petstoreserviceproduct
  template:
    metadata:
      labels:
        app: aks-petstoreserviceproduct
    spec:
      containers:
      - name: aks-petstoreserviceproduct
        image: mypetstoreecr.azurecr.io/petstoreserviceproduct:latest
        ports:
        - containerPort: 80
        env:
        - name: PETSTOREPRODUCTSERVICE_SERVER_PORT
          value: "80"
       # - name: spring.config.name
        #  value: application_with_everything_enabled
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "01a85565-3834-4171-ba2f-dbd19f4cca49"
        
---
apiVersion: v1
kind: Service
metadata:
  name: aks-petstoreserviceproduct 
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aks-petstoreserviceproduct
