name: Pet Store App Build and Push to ACR

env:
  AZURE_CONTAINER_REGISTRY: mypetstoreecr.azurecr.io
  AZURE_CONTAINER_REGISTRY_USERNAME: mypetstoreecr

on:
  push:
    branches:
      - main
    paths:
      - petstore/petstoreapp/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build petstore/petstoreapp -t ${{ env.AZURE_CONTAINER_REGISTRY }}/petstoreapp:latest
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ env.AZURE_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.PETSTORECRSECRET }}
    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/petstoreapp:latest
